# Delta circle.yml

version: 2

general:
  branches:
      ignore:
          - develop

jobs:
  build:
    machine: true
    working_directory: /home/circleci/project
    steps:

        - checkout
        
        - run:
            name: look at cache
            command: |
                ls ~/
        
        - restore_cache:
            keys: # Restores the first one it finds
                - gittest-{{ .Branch }}
                - gittest-master
        
        - run:
            name: look at cache
            command: |
                ls ~/
                if [ -d ~/mycache ]; then
                    ls ~/mycache
                fi
        
        - run:
            name: remake cache
            command: |
                rm -rf ~/mycache || :
                mkdir ~/mycache
                touch ~/mycache/$CIRCLE_BUILD_NUM

        - save_cache:
            key: gittest-{{ .Branch }}-{{ epoch }} # {{ epoch }} gets ignored when restoring above
            paths:
                - "~/mycache"
