# Delta circle.yml

version: 2
jobs:
  build:
    machine: true
    working_directory: /home/circleci/project
    steps:

        - run:
            name: setup environment
            command: |
                echo 'export BUILD_STACK_ID=circ$CIRCLE_BUILD_NUM' >> $BASH_ENV
                echo "circ$CIRCLE_BUILD_NUM"

        - checkout
        
        - run:
            name: look at cache
            command: |
                ls ~/
        
        - restore_cache:
            keys: 
                - gittest-{{ .Branch }}
                - gittest-master
        
        - run:
            name: look at cache
            command: |
                ls ~/
                if [ -d ~/mycache ]; then
                    ls ~/mycache
                fi
        
        - run:
            name: make cache
            command: |
                mkdir -p ~/mycache
                touch ~/mycache/$CIRCLE_BUILD_NUM

        - save_cache:
            key: gittest-{{ .Branch }}-{{ epoch }}
            paths:
                - "~/mycache"
